### ISSUE TITLE
swift build error

### ISSUE THREAD

**Issue by tinysun212** [tumasgiu/W32ExperimentStepThree#4]
`swift build` generates some errors
1. Missing separator `,` between two Packages in `Package.swift`
   `.Package(url: "https://github.com/tumasgiu/Win32.git", majorVersion: 0, minor: 2)` 
   `,`
   `.Package(url: "https://github.com/tumasgiu/GDI.git", majorVersion: 0, minor: 1)`
2. Duplicated cloning Win32 repo, since `https://github.com/tumasgiu/Win32.git` in W32ExperimentStepThree is not same to `https://github.com/tumasgiu/Win32` in GDI.
   It will be better to add suffix '.git' to the URLs in GDI/Package.swift

**Comment by tumasgiu** [comment]
Thanks for the report!
